import Header from "./components/header";
import Player from "./components/player";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <div>
      <Header />
      {children}
      <Player />
    </div>
  );
}
